/// Communes d'Haïti organisées par département
class HaitiLocations {
  static const Map<String, List<String>> communesByDepartment = {
    'Artibonite': [
      'Anse-Rouge',
      'Dessalines',
      'Desdunes',
      'Ennery',
      'Gonaïves',
      'Grande Saline',
      'Gros-Morne',
      'L\'Estère',
      'Marmelade',
      'Petite-Rivière-de-l\'Artibonite',
      'Saint-Marc',
      'Saint-Michel-de-l\'Attalaye',
      'Terre-Neuve',
      'Verrettes',
    ],
    'Centre': [
      'Belladère',
      'Cerca-Carvajal',
      'Cerca-la-Source',
      'Hinche',
      'Lascahobas',
      'Maïssade',
      'Mirebalais',
      'Savanette',
      'Thomassique',
      'Thomonde',
    ],
    'Grand\'Anse': [
      'Abricots',
      'Anse-d\'Hainault',
      'Beaumont',
      'Bonbon',
      'Chambellan',
      'Corail',
      'Dame-Marie',
      'Jérémie',
      'Les Irois',
      'Moron',
      'Pestel',
      'Roseaux',
    ],
    'Nippes': [
      'Anse-à-Veau',
      'Arnaud',
      'Baradères',
      'L\'Asile',
      'Miragoâne',
      'Petit-Trou-de-Nippes',
      'Petite-Rivière-de-Nippes',
      'Plaisance-du-Sud',
    ],
    'Nord': [
      'Acul-du-Nord',
      'Bahon',
      'Borgne',
      'Cap-Haïtien',
      'Dondon',
      'Grande-Rivière-du-Nord',
      'Lenbe',
      'Limonade',
      'Milot',
      'Pignon',
      'Pilate',
      'Plaine-du-Nord',
      'Plaisance',
      'Port-Margot',
      'Quartier-Morin',
      'Ranquitte',
      'Saint-Raphaël',
    ],
    'Nord-Est': [
      'Carice',
      'Ferrier',
      'Fort-Liberté',
      'Mombin-Crochu',
      'Mont-Organisé',
      'Ouanaminthe',
      'Perches',
      'Sainte-Suzanne',
      'Terrier-Rouge',
      'Trou-du-Nord',
      'Vallières',
    ],
    'Nord-Ouest': [
      'Anse-à-Foleur',
      'Baie-de-Henne',
      'Bombardopolis',
      'Chansolme',
      'Jean-Rabel',
      'La Tortue',
      'Môle-Saint-Nicolas',
      'Port-de-Paix',
      'Saint-Louis-du-Nord',
    ],
    'Ouest': [
      'Arcahaie',
      'Cabaret',
      'Carrefour',
      'Cité Soleil',
      'Cornillon',
      'Croix-des-Bouquets',
      'Delmas',
      'Gressier',
      'Ganthier',
      'Grand-Goâve',
      'Kenskoff',
      'Kenscoff',
      'Léogâne',
      'Petit-Goâve',
      'Pétion-Ville',
      'Port-au-Prince',
      'Tabarre',
      'Thomazeau',
    ],
    'Sud': [
      'Aquin',
      'Arniquet',
      'Cayes',
      'Cavaillon',
      'Chantal',
      'Chardonnières',
      'Côteaux',
      'Île-à-Vache',
      'Les Anglais',
      'Les Cayes',
      'Maniche',
      'Port-à-Piment',
      'Port-Salut',
      'Roche-à-Bateau',
      'Saint-Jean-du-Sud',
      'Saint-Louis-du-Sud',
      'Torbeck',
    ],
    'Sud-Est': [
      'Anse-à-Pitres',
      'Bainet',
      'Belle-Anse',
      'Cayes-Jacmel',
      'Côtes-de-Fer',
      'Grand-Gosier',
      'Jacmel',
      'La Vallée',
      'Marigot',
      'Thiotte',
    ],
  };

  /// Obtenir toutes les communes d'un département
  static List<String> getCommunesByDepartment(String? department) {
    if (department == null) return [];
    return communesByDepartment[department] ?? [];
  }

  /// Obtenir toutes les communes (triées alphabétiquement)
  static List<String> getAllCommunes() {
    final allCommunes = <String>[];
    communesByDepartment.forEach((_, communes) {
      allCommunes.addAll(communes);
    });
    allCommunes.sort();
    return allCommunes;
  }
}
